/**
 * Post-generation quality filter.
 *
 * Every candidate message runs through this before we log or ship it.
 * Failures return a reason the caller uses to decide whether to retry
 * (once, with the rejected message added to the dedup list) or skip the tick.
 *
 * Per-channel config (Fix 7): Telegram is a Miami community voice, Buffer is
 * a professional observer voice. Same function, different thresholds +
 * different banned patterns.
 */

export type Channel = "telegram" | "buffer";

export type StyleGuardConfig = {
  emojiDensityMax: number;       // emoji count / word count — reject if above
  emojiCountMax: number;         // absolute hard cap on emoji count per message
  capsRatioMax: number;          // uppercase-letter ratio — reject if above
  capsRatioMinLength: number;    // only apply caps check if message length > this
  terminalEmojiRejectRate: number; // probability of rejecting messages ending in 🔥/😤
  jaccardSimilarityMax: number;  // per-channel max similarity vs recent messages
  bannedPatterns: { pattern: RegExp; reason: string }[];
};

// Patterns banned on BOTH channels — these are actual observed repetitions
// from the April 10-16 Telegram export.
const BANNED_PATTERNS_UNIVERSAL: { pattern: RegExp; reason: string }[] = [
  // está/están + X-ando + a + Y  — matches "está machacando a Cleveland" AND "están humillando a los Twins"
  { pattern: /est[áa]n?\s+\w+ando\s+a\s+\w/i, reason: "banned_template:está_X-ando_a_Y" },
  { pattern: /pr[áa]ctica\s+de\s+\w+/i, reason: "banned_template:práctica_de_X" },
  { pattern: /como\s+si\s+fuera\s+pr[áa]ctica/i, reason: "banned_template:como_si_fuera_practica" },
];

// Patterns banned only on public Buffer channels (X/Threads). Readable as
// try-hard on broader reach.
const BANNED_PATTERNS_BUFFER_ONLY: { pattern: RegExp; reason: string }[] = [
  { pattern: /chose\s+violence/i, reason: "banned_template:chose_violence" },
  { pattern: /nobody\s+wants\s+to\s+win/i, reason: "banned_template:nobody_wants_to_win" },
];

// Telegram: Miami community voice. Generous on emoji + caps.
export const TELEGRAM_CONFIG: StyleGuardConfig = {
  emojiDensityMax: 0.70,
  emojiCountMax: 4,
  capsRatioMax: 0.90,
  capsRatioMinLength: 40, // allow short caps bursts like "VAMOSSS" unchecked
  terminalEmojiRejectRate: 0.10,
  jaccardSimilarityMax: 0.5,
  bannedPatterns: BANNED_PATTERNS_UNIVERSAL,
};

// Buffer (X + Threads): sharp-bettor voice with sazón. English-heavy, some Spanglish allowed.
// Relaxed caps (0.50) so proper-noun bursts ("LEAD CHANGE", "MIAMI") read clean.
export const BUFFER_CONFIG: StyleGuardConfig = {
  emojiDensityMax: 0.30,
  emojiCountMax: 2,
  capsRatioMax: 0.50,
  capsRatioMinLength: 30,
  terminalEmojiRejectRate: 0.40,
  jaccardSimilarityMax: 0.5,
  bannedPatterns: [...BANNED_PATTERNS_UNIVERSAL, ...BANNED_PATTERNS_BUFFER_ONLY],
};

export function getConfigForChannel(channel: Channel): StyleGuardConfig {
  return channel === "telegram" ? TELEGRAM_CONFIG : BUFFER_CONFIG;
}

const EMOJI_REGEX = /\p{Extended_Pictographic}/gu;
const TRAILING_EMOJI_REGEX = /[\u{1F525}\u{1F624}]\s*$/u; // 🔥 😤 at end

/**
 * Word-level Jaccard similarity between two strings (case-insensitive,
 * ignoring short stopwords and punctuation).
 */
function jaccardSimilarity(a: string, b: string): number {
  const tokenize = (s: string) =>
    new Set(
      s
        .toLowerCase()
        .replace(/[^\p{L}\p{N}\s]/gu, " ")
        .split(/\s+/)
        .filter((t) => t.length > 2)
    );
  const A = tokenize(a);
  const B = tokenize(b);
  if (A.size === 0 || B.size === 0) return 0;
  const inter = new Set<string>();
  for (const x of A) if (B.has(x)) inter.add(x);
  const union = new Set<string>([...A, ...B]);
  return inter.size / union.size;
}

/**
 * Stable 0..1 hash used to gate the "terminal emoji quota" rule
 * deterministically (so retries with the same message don't re-pass the
 * quota check — they must actually change the text).
 */
function stableHash01(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0) / 0xffffffff;
}

export type StyleVerdict = { ok: true } | { ok: false; reason: string };

/**
 * Validate a candidate message against channel-specific style rules.
 *
 * @param message       Text generated by Claude (post-cleanup)
 * @param recentMessages Prior messages to dedup against (should be fetched for this same channel)
 * @param channel       "telegram" or "buffer"
 */
export function validateStyle(
  message: string,
  recentMessages: string[] = [],
  channel: Channel = "telegram"
): StyleVerdict {
  const msg = message.trim();
  if (!msg) return { ok: false, reason: "empty" };

  const config = getConfigForChannel(channel);

  // Rule 0: em-dash hard ban on both channels.
  // GPT-ism tell. Prompts explicitly forbid it. Reject with no retry-repair
  // path — the generator re-prompts once; if Claude keeps emitting em dashes
  // the tick is skipped entirely.
  if (/\u2014/.test(msg)) {
    return { ok: false, reason: `em_dash_banned(${channel})` };
  }

  // Rule 1: emoji count + density
  // Density check only applies when the message has enough words for the
  // ratio to be meaningful (>= 4 words). For short hype bursts like
  // "VAMOSSSS 🔥" or "AYY PAPA 🔥" the density ratio would always be 100%
  // even though the message is obviously fine. The absolute emojiCountMax
  // still protects against emoji walls at any message length.
  const emojiMatches = msg.match(EMOJI_REGEX) || [];
  const wordCount = msg.replace(EMOJI_REGEX, " ").split(/\s+/).filter(Boolean).length;
  if (emojiMatches.length > config.emojiCountMax) {
    return { ok: false, reason: `emoji_count_too_high:${emojiMatches.length}>${config.emojiCountMax}(${channel})` };
  }
  if (wordCount >= 4 && emojiMatches.length / wordCount > config.emojiDensityMax) {
    return { ok: false, reason: `emoji_density_too_high(${channel})` };
  }

  // Rule 2: caps ratio. Only applied above channel-specific min length.
  if (msg.length > config.capsRatioMinLength) {
    let upper = 0;
    let lettersTotal = 0;
    for (const ch of msg) {
      if (ch >= "A" && ch <= "Z") { upper++; lettersTotal++; }
      else if (ch >= "a" && ch <= "z") { lettersTotal++; }
    }
    if (lettersTotal > 0 && upper / lettersTotal > config.capsRatioMax) {
      return { ok: false, reason: `caps_ratio_too_high(${channel})` };
    }
  }

  // Rule 3: banned patterns (per channel)
  for (const { pattern, reason } of config.bannedPatterns) {
    if (pattern.test(msg)) return { ok: false, reason };
  }

  // Rule 4: Jaccard similarity vs recent messages (per channel context)
  for (const rec of recentMessages) {
    const sim = jaccardSimilarity(msg, rec);
    if (sim > config.jaccardSimilarityMax) {
      return { ok: false, reason: `similar_to_recent:jaccard=${sim.toFixed(2)}(${channel})` };
    }
  }

  // Rule 5: terminal-emoji probabilistic rejection (per channel rate)
  if (TRAILING_EMOJI_REGEX.test(msg)) {
    const score = stableHash01(msg);
    // Reject when stableHash score is ABOVE (1 - rejectRate).
    // Telegram rejectRate=0.10 → reject when score>0.9 (10% of messages).
    // Buffer   rejectRate=0.40 → reject when score>0.6 (40% of messages).
    if (score > 1 - config.terminalEmojiRejectRate) {
      return { ok: false, reason: `terminal_emoji_quota(${channel})` };
    }
  }

  return { ok: true };
}

/**
 * Exposed for tests.
 */
export const __internals = { jaccardSimilarity, stableHash01 };
